# This stage names are used for stashing and un-stashing of files

initS4sdkPipeline:
  unstash: []
  stashes:
    - name: "SOURCE"
      includes: "**"
      excludes: "**/.git/**, s4hana_pipeline/reports/**, s4hana_pipeline/maven_local_repo/**"
    #    Following stash will contain only empty directory.
    #    This is required to support the concurrency in the stashing mechanism where
    #    we merge the stashes from multiple stages into one.
    - name: "REPORTS"
      includes: "s4hana_pipeline/reports/**"
    - name: "M2"
      includes: "s4hana_pipeline/maven_local_repo/**"

build:
  unstash: ["SOURCE", "M2"]
  stashes:
    - name: "M2"
      includes: "s4hana_pipeline/maven_local_repo/**"
    - name: "TARGET"
      includes: "*.mtar, **/target/**"
    - name: "NODE_MODULES"
      includes: "**/node_modules/**"
    - name: "PACKAGE_LOCK"
      includes: "**/package-lock.json, **/npm-shrinkwrap.json"
    - name: "GENERATED_CAP_FILES"
      includes: "**/src/main/resources/edmx/**, db/src/gen/**, gen/**"

unitTests:
  unstash: ["SOURCE", "M2", "TARGET", "NODE_MODULES"]
  stashes:
    - name: "REPORTS"
      merge: true
      includes: "s4hana_pipeline/reports/**"

backendIntegrationTests:
  unstash: ["SOURCE", "M2", "TARGET", "NODE_MODULES", "GENERATED_CAP_FILES"]
  stashes:
    - name: "REPORTS"
      merge: true
      includes: "s4hana_pipeline/reports/**"

frontendIntegrationTests:
  unstash: ["SOURCE", "NODE_MODULES", "GENERATED_CAP_FILES"]
  stashes:
    - name: "REPORTS"
      merge: true
      includes: "s4hana_pipeline/reports/**"

staticCodeChecks:
  unstash: ["SOURCE", "TARGET", "REPORTS", "M2"]
  stashes:
    - name: "REPORTS"
      merge: true
      includes: "s4hana_pipeline/reports/**"

lint:
  unstash: ["SOURCE"]

checkmarxScan:
  unstash: ["SOURCE", "TARGET"]
  stashes: []

whitesourceScan:
  unstash: ["SOURCE", "M2", "NODE_MODULES", "PACKAGE_LOCK"]
  stashes: []

sourceClearScan:
  unstash: ["SOURCE", "M2", "NODE_MODULES"]
  stashes: []

additionalTools:
  unstash: ["SOURCE", "M2", "NODE_MODULES"]
  stashes: []

sonarQubeScan:
  unstash: ['SOURCE', 'M2', 'NODE_MODULES', 'REPORTS', 'TARGET']
  stashes: []

fortifyScan:
  unstash: ["SOURCE", "M2", "TARGET"]
  stashes: []

npmAudit:
  unstash: ["SOURCE", "PACKAGE_LOCK"]
  stashes: []

frontendUnitTests:
  unstash: ["SOURCE", "NODE_MODULES"]
  stashes:
    - name: "REPORTS"
      merge: true
      includes: "s4hana_pipeline/reports/**"

endToEndTests:
  unstash: ["SOURCE", "TARGET", "NODE_MODULES"]
  stashes: []

performanceTests:
  unstash: ["SOURCE", "TARGET"]
  stashes:
    - name: "REPORTS"
      merge: true
      includes: "s4hana_pipeline/reports/**"

s4SdkQualityChecks:
  unstash: ["SOURCE", "M2", "TARGET", "REPORTS"]
  stashes:
    - name: "REPORTS"
      includes: "s4hana_pipeline/reports/**"

artifactDeployment:
  unstash: ["SOURCE", "TARGET", "NODE_MODULES"]
  stashes: []

productionDeployment:
  unstash: ["SOURCE", "TARGET", "NODE_MODULES"]
  stashes: []

postPipelineHook:
  unstash: ["SOURCE"]
  stashes: []
